### ISSUE TITLE
No sensor information on associated topics

### ISSUE THREAD

**Issue by ladrians** [CygLiDAR-ROS/cld1a0_pcl#15]
I am evaluating the cyglidar_d1 node on ROS Melodic 1.14.12. I am interested in the 3D option.
I do not see any information on the rviz, node launch is as follows

```
[ INFO] [1636141645.590000873]: FREQUENCY: 0 (0) / PULSE CONTROL: 0, DURATION: 10000 (2710)
QApplication: invalid style override passed, ignoring it.
[ INFO] [1636141651.320265687]: PACKET SENT (START, 2)
[ INFO] [1636141652.321271964]: PACKET_FREQUENCY HAS BEEN UPDATED [0]
	PACKET: 5a,77,ff,2,0,f,0,d
[ INFO] [1636141653.322193677]: PACKET_INTEGRATION_TIME HAS BEEN APPLIED [10000]
	PACKET: 5a,77,ff,3,0,c,0,0,f
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
```

I downloaded the Windows utility and could see the 2D information, then changed some baudare configuration, and other options from the utility for exploration and cannot see anything anymore.

Checked with screen on linux and putty on windows and cannot see any packet data on the serial port.
Tried with the 3 options: 3000000 250000 115200 but nothing useful I could add to this ticket.
Not sure if I can reset the sensor for factory data to start from scratch? Any tip on how to troubleshoot it?
regards,

**Comment by cygbot-ros-support** [comment]
Hello, ladrians.
We apologize for the late reply on your question.

For the 3D point clouds on the rviz, you need to check the argument version in the **_cyglidar.launch_** file is correct for 3D output (1 or 2, 2 for 2D and 3D both).
Since the **_cyglidar.launch_** file contains **_PointCloud2_**, topic set as **_scan_3D_**, it should print the 3D points on the screen. If it doesn't work, please try _**rostopic echo**_, see if the data are printed on the terminal.

We're sorry to say that there's no way to reset on the windows viewer manually nor factory data setting, but the data you set before should go back to default setting as you turn it off and on again. We are also wondering if it was working with 2D and 3D when you got the package.

If it doesn't work, please comment below with the specific trouble.
Thank you.

**Comment by ladrians** [comment]
Hi thanks for the reply. Finally we got it working but not sure what was the change. We got back to the defaults and tested a couple of days later and worked.

I have a question, we located the sensor at 45 degrees pointing to the floor. We found that in some floor surfaces (such as carpet) nothing is detected, we expected that floor surfaces should always de detected on the scan_3D message? Do we need to provide a bag or similar if further analysis is needed?
regards,

**Comment by cygbot-ros-support** [comment]
We're glad that it worked.
As the baudrate is changed, it's fixed to the changed value, but not the others.

Because it's based on reflection of light, some materials or black color may not be detected on certain duration setting.
With the viewer, the carpet may be detected if you change the **_Duration_** value.
In the ROS driver, you can adjust the value in the **_cyglidar.launch_** file, change the **_default_** of argument **_pulse_duration_**.

Please try and see if it works.
Thank you.

**Comment by ladrians** [comment]
Hi thanks for the tips, using 10k duration was the best option we could get, when lowering the value starts loosing some data.
closing the ticket, thanks
